FROM timescale/timescaledb-postgis:2.3.0-pg13

COPY ./schemas/surface/surface_dump.sql /docker-entrypoint-initdb.d/1.sql
COPY ./schemas/surface/wx_station.sql /docker-entrypoint-initdb.d/2.sql
COPY ./schemas/surface/raw_data_station_id_108.sql /docker-entrypoint-initdb.d/3.sql
COPY ./schemas/surface/raw_data_station_id_14.sql /docker-entrypoint-initdb.d/4.sql
