FROM timescale/timescaledb-postgis:latest-pg12
# COPY ./schemas/wmdr/wmdr_sql.sql /docker-entrypoint-initdb.d/1.sql
COPY ./schemas/wmdr/tables/* /schemas/
COPY ./schemas/wmdr/settings.sql /docker-entrypoint-initdb.d/1.sql
RUN cat /schemas/*  >| /docker-entrypoint-initdb.d/2.sql