FROM postgres:13
COPY ./scripts/entrypoints/clide.sh /docker-entrypoint-initdb.d/1.sh
COPY ./schemas/clide/clidedb_schema.sql /docker-entrypoint-initdb.d/2.sql
COPY ./schemas/wmdr/ /wmdr_init_scripts/
RUN cat /wmdr_init_scripts/*.sql >| /docker-entrypoint-initdb.d/3.sql
RUN rm -rf /wmdr_init_scripts/
